default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  queue:
    <<: *default
    database: storage/development-queue.sqlite3
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: storage/development-cache.sqlite3
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: storage/development-cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  queue:
    <<: *default
    database: storage/test-queue.sqlite3
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: storage/test-cache.sqlite3
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: storage/test-cable.sqlite3
    migrations_paths: db/cable_migrate
production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  queue:
    <<: *default
    database: storage/production-queue.sqlite3
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: storage/production-cache.sqlite3
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: storage/production-cable.sqlite3
    migrations_paths: db/cable_migrate